Update index.test.js: Fix relative path
Causes enzyme tests out of the box to error.

Running enzyme tests.
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
Cannot find module '../lib/components'
Error: Cannot find module '../lib/components'